# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Paige Smith-Hogan
tagline:          'Paige is cool'
description:      'I like yogurt'
url:              http://apaigesh.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

gems:
  - jekyll-paginate
  - jekyll-gist
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
